security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        api_keys:
            memory:
                users:
                    TESTAPIKEY: {}

    encoders:
        App\Entity\User:
            algorithm: auto
        Symfony\Component\Security\Core\User\User: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            provider: api_keys
            stateless: true
            guard:
                authenticators:
                    - App\Security\ApiAuthenticator
        main:
            anonymous: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\FormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

    #access_control:
    #    - { path: ^/admin, roles: ROLE_ADMIN }
