security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    encoders:
        App\Entity\User:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

    #access_control:
    #    - { path: ^/admin, roles: ROLE_ADMIN }
