security:
    providers:
        in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            anonymous: false
        main:
            anonymous: true

    #access_control:
    #    - { path: ^/admin, roles: ROLE_ADMIN }
